# Generated by Django 5.0.2 on 2024-02-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authFlow', '0004_alter_studentregistermodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
            ],
        ),
    ]
