# Generated by Django 5.0.2 on 2024-02-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authFlow', '0008_rename_customuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
