# Generated by Django 5.0.2 on 2024-03-04 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentAPIs', '0002_uploadedfile_alter_studentinfo_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='image',
            field=models.FilePathField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
