# Generated by Django 5.0.2 on 2024-03-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentAPIs', '0003_delete_uploadedfile_studentinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
